[package]
name = "libsql-nvim-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[features]
macros = []

[dependencies]
proc-macro-error = "1.0.4"
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = "2.0.58"
mlua.workspace = true
serde.workspace = true
